name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: [qiniu, ubuntu-24.04]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Go environment
        run: |
          echo "GOPATH=${RUNNER_TEMP}/go" >> "$GITHUB_ENV"
          echo "GOBIN=${RUNNER_TEMP}/go/bin" >> "$GITHUB_ENV"
          echo "GOMODCACHE=${RUNNER_TEMP}/go/pkg/mod" >> "$GITHUB_ENV"
          echo "GOCACHE=${RUNNER_TEMP}/go-build-cache" >> "$GITHUB_ENV"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
